### ISSUE TITLE
license contradiction

### ISSUE THREAD

**Issue by znalo** [axfreeman/capitalism-9.0#1]
Hello,

The file https://github.com/axfreeman/capitalism-9.0/blob/master/readme.md 
contains the following two pieces of text both under the heading "legal and license stuff":

1:
"""
The app, documentation, and code (in other words, everything on this site) is copyright. It is free for you to use and distribute but you must acknowledge it, and you can't make money from it.
"""

and ... 2:
"""
All files in this repository are part of the Capitalism Simulation, abbreviated to CapSim in the remainder of this project. Capsim is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation
"""

The problem is part 1 is incompatible with part 2, as the unmodified GPL doesn't allow for prohibitions against particular classes of use (like 'making money').  An example of a well-meant modification would be a prohibition against military use of a particular piece of code.  If such a license were applied to GNU/Linux, it  could have prevented the Venezuelan Navy from reducing their dependence on US-made operating systems developed under the jurisdiction of the USAPATRIOT act and the direct reach of the NSA.

I'm aware that for many people, licensing considerations are not very important, but I would suggest the best protection against someone making themselves rich on the basis of your work would be the fact that the work is already available for free, and that any modifications can't be distributed without providing corresponding source code for free, and under similar conditions.

Even an exception prohibiting 'making money' can create problems because it complicates the picture and creates uncertainty in corner cases where things like media cost recovery of hosting cost recovery (in, the hypothetical case of ) might be construed as 'making money'.  Relying on the presumed goodwill of publishers of contradictorily licensed software is not something small, poorly resourced outfits can afford, meaning they'd likely simply not redistribute the CapSim software at all, which would be a pity - I'd like to see elements of CapSim widely distributed in large free software collections.

Finally, I'd say releasing under the GPL is useful and good as the license is well established and because of past battles fought by programmers, the GPL is relatively well institutionally accommodated.  Releasing under a modified or special invented license like "use only for good, not evil" is counterproductive, making it more difficult to persuade universities and similar large organisations to allow people to contribute modifications on 'company time'. 

Anyway - enough words.  

  -AA.

[http://www.librarything.com/profile/znalo]

**Comment by axfreeman** [comment]
Hi Ambrose

 

As you probably realise I’m new to GPL copyright issues so thanks for this advice.

 

From what you say, would I be right in concluding that I should delete the words ‘but you can’t make money from it’?

 

Best

Alan

**Comment by znalo** [comment]
Hi Alan,

Yes, I think your proposed edit would improve and harmonise things.

I look forward to eventually playing with the model.

Regards,

  -AA.

**Comment by axfreeman** [comment]
Thanks for your interest. As you may have noticed, I haven’t done  anything on it for a while – basically once I was satisfied the concept would work.

I will be coming back to it in due course, basically once I have completed a book on it with the math on which it is based.

The model will accompany the book. I’m hoping to port it to a web version before then and this may be the next step – I am getting too many reports of problems running the executable.

 

Of course, any comments before then are absolutely welcome, and thanks for the advice.

 

Regards

Alan
