### ISSUE TITLE
Mathematical Foundations paper

### ISSUE THREAD

**Issue by dentarthur** [axfreeman/capitalism-9.0#2]
1. Typo p40 and Table 6. New MEV should be $540/y350 not $540/y340. Please verify asap to confirm my understanding of your MELT concept (which I disagree with and may perhaps misunderstand).

2. Previous page example confused me as did not use figures from Table 6 when explaining MEV. Better to mention specific row and column.

3. Still missing from docs folder.

4. Should link from top level as well as docs README.md

5.  Use # Title (with space) not #Title for correct display in markdown .md files.

##Title does not highlight Title nor hide ##

## Title is correct.

**Comment by axfreeman** [comment]
Hi

Will look into it. Next few weeks are still tight. 3 trips in 3 weeks… 

Should ease up after that. I do appreciate your looking at this and will certainly respond as soon as I can


A

PS do you speak/read Spanish? I had to do a skype seminar for UNAM in Mexico (I  think I mentioned it?) and prepared extensive slides.

Not especially useful for understanding MELT but has bearing on rate of profit

 

A

**Comment by dentarthur** [comment]
1. 4 weeks delay suits me fine as I need to catch up reading.

2. spent 2-3 hours today with friend Tom working through just the Simple
Reproduction project 1 of your app. Tom and partner Susan (an accountant)
are working through "Ed George's Reading Notes" on Capital vol2 chapters
20-21 reproduction schemes with me. Tom says willing to work on detailed
feedback for completion of your app with me.

3. We both request that you fix one thing in particular that should be a
quick fix, so as to make it significantly easier for us and others to do
so. The column layout collapses when you switch from one project to another
and has to be manually rearranged. To understand where you are going we
need to keep progressing through the various projects without wasting time
on that while focussing on the real issues of an unfinished app and
documentation. So I will leave the app until after you get back and
hopefully issue a quick fix of just that issue.

4. Simply allowing the user to save and reload column positions is
sufficient to avoid the time wasting. Later it would of course be desirable
to also use whatever facilities the framework has so that a reasonably good
default layout is calculated according to the user's screen and window
dimensions which will vary from yours as developer.

5. I will probably write more while you are still busy with travel etc. Not
expecting replies until later.

**Comment by dentarthur** [comment]
Forgot to answer. No I don't have any Spanish.
